### ISSUE TITLE
Missing types in typings

### ISSUE THREAD

**Issue by XLeapZan** [voxeet/voxeet-sdk-web#13]
Hi, we are trying make use of your type definitions (SDK 3.7.0). 

We have compile errors using your typings, specifically we have issues with these files:

a) Some files have imports from **@dolby-dvc** which appears to be an internal project not available via npm,

- types\events\conference\ConferenceLeft.d.ts
- types\models\CaptureMode.d.ts

b) Path issues / files do not exist
- types\services\conference\ConferenceService.d.ts
  - ConferenceManager

- types\services\index.d.ts has path issues the imports
  - /telemetry/TelemetryService
  - /browserevent/BrowserEventService

**Comment by FabienLavocat** [comment]
Hi @XLeapZan
In you `tsconfig.json`, please set the flag `skipDefaultLibCheck` to `true`, so the compiler will not attempt to type check external libraries.
See: https://www.typescriptlang.org/tsconfig#skipDefaultLibCheck

**Comment by XLeapZan** [comment]
Awesome. Thanks
