### ISSUE TITLE
SessionError: A session has already been opened

### ISSUE THREAD

**Issue by MarkusPint** [voxeet/voxeet-sdk-web#14]
`
    if (!VoxeetSDK.session.isOpen()) {
      await VoxeetSDK.session.open({ name: 'testname', externalId: 1 });
    }
`

Intermittently this code is producing an error:
"SessionError: A session has already been opened"

How can this be possible? We've taken care to check that a session is not open before we try to open one, but still it sometimes throws this error.

**Comment by FabienLavocat** [comment]
https://github.com/dolbyio-samples/comms-sdk-web-getting-started/issues/30
