### ISSUE TITLE
muteOutput

### ISSUE THREAD

**Issue by MarkusPint** [voxeet/voxeet-sdk-web#15]
Hi,
I noticed the iOS SDK has this function:
https://docs.dolby.io/communications-apis/docs/ios-client-sdk-conferenceservice#muteoutput

Would be very useful to us. Is there any way to do this right now with Web SDK?

Or is the only way to grab "vxt-audio" element from DOM and set it's volume property to "0" ?

**Comment by FabienLavocat** [comment]
Hi @MarkusPint,
This is not an API we have for the Web SDK, however you can set the volume on the audio element.
```javascript
const audio = document.getElementById('audio-00000000-0000-0000-0000-000000000000');
audio.volume = 0;
```
Fabien

**Comment by FabienLavocat** [comment]
We have introduced the [muteOutput](https://docs.dolby.io/communications-apis/docs/js-client-sdk-conferenceservice#muteoutput) function in the Web SDK version [3.10](https://github.com/voxeet/voxeet-sdk-web/releases/tag/3.10.0).
