### ISSUE TITLE
Question on Conference creation limits

### ISSUE THREAD

**Issue by MarkusPint** [voxeet/voxeet-sdk-web#16]
Hi,
Our use case requires creating, joining and leaving of conferences by a user sometimes 100-200 times in an hour.

Are there any limits/throttling on conference.create or conference.join methods?

**Comment by FabienLavocat** [comment]
Hi @MarkusPint could you please explain a bit more why you would need to create/join 100-200 times an hour?

**Comment by MarkusPint** [comment]
1) We use Dolby SDK in a Chrome extension
2) This Chrome extension works on sites like Hubspot that enable users to call their sales leads right from the site.
3) Once we detect a call is happening we start streaming the call's audio stream it into our application using Dolby SDK, to enable other users to listen to it in our app.
4) Most users will dial like to like 50-100 numbers in an hour, which will mean 50-100 conference creations/joins by the person dialing. Most of these conferences are short lived, because most people don't pick up or it's an answering machine.
5) As soon as a "dial" ends we also kill the Dolby conference.

Why I am asking this is because till now we've been kind of re-using a conference of a single user by passing an "alias" during "Conference" creation. This alias would be unique per user. So if a user left it, but came back to it before it's "ttl" ran out, he would re-join the previous conference.

The problem is that we've also now added recording to these Dolby conferences and because sometimes the previous "Conference" is re-used the recordings from Dolby are not clearly separated by "dial".

So now we want to stop using "alias", which would mean 1 dial = 1 Dolby conference. Just want to make sure we're not going to hit some kind of limitation.

**Comment by FabienLavocat** [comment]
Thanks a lot for describing this. We can support this scenario of creating short lived conferences.

You are correct, if you are reusing the same alias before the conference TTL has triggered, then it will be considered as the same conference and so you will get the same recording output.

**Comment by MarkusPint** [comment]
Thank you for the help Fabien!

**Comment by FabienLavocat** [comment]
You're welcome. Don't hesitate to reach out to us, we can have a technical discussion about your project. Send an email to support@dolby.io and I will pick up the message and reach out back to you.
