### ISSUE TITLE
Current conference participants map is always empty

### ISSUE THREAD

**Issue by vodemn** [voxeet/voxeet-sdk-web#18]
Hello! I'm trying to access the current conference participants list, but unfortunately it is always empty for some reason. At the same time, for example, `ActiveParticipants` event does contain all the participants.

**SDK version 3.8.5**

**Comment by FabienLavocat** [comment]
If, while in a conference, you print the list of [participants](https://docs.dolby.io/communications-apis/docs/js-client-sdk-conferenceservice#participants), it is empty?
```js
console.log(VoxeetSDK.conference.participants);
```

**Comment by vodemn** [comment]
I'm accessing this list through `VoxeetSDK.conference.current.participants`. Is there any difference by the way? Should I access this list throught the current conference or I can do it directly from conference service?

**Comment by FabienLavocat** [comment]
I've never really used the `VoxeetSDK.conference.current.participants` only `VoxeetSDK.conference.participants` but for me the result is exactly the same.
<img width="428" alt="image" src="https://user-images.githubusercontent.com/4154532/230497072-dfb487c7-ff4c-4207-80ed-603946b26a75.png">
Could you please share maybe a sample app where you can reproduce this issue or logs or maybe a conference ID so I can look at the logs on our side.

**Comment by vodemn** [comment]
@FabienLavocat  Here is the conference id: `73acdcb7-6dbe-4b3b-9a5b-d39b8be87e6f`

**Comment by FabienLavocat** [comment]
I see a lot of errors in this conference, like the internet connection seems very unstable. Could you give a try using this sample application: https://github.com/dolbyio-samples/comms-sdk-web-sample
Connect to a conference, then in the console type:
```js
console.log(VoxeetSDK.conference.participants);
```

**Comment by vodemn** [comment]
All the participants are present, when logging them:
```javascript
console.log(VoxeetSDK.conference.participants);
```
So problem is somewhere in my code. Thank for your assistance!
