### ISSUE TITLE
The remote-view freezes, if a Chromium-based browser participates on an Android device

### ISSUE THREAD

**Issue by Schaeri** [voxeet/voxeet-sdk-web#19]
The error occurs, if a participant joins a conference, using an Android device with a Chromium-based browser. Upon joining, the remote view of the other participant will work as expected for a few seconds. Then the video freezes, but the audio still works as expected.

This only happens, if the device uses a Chromium-based browser. We tested this on a handful of other Android devices also with different mobile network providers and WLAN.
On non-Chromium browsers e.g. Firefox, the issue does not occur.
  
The reproduction of the problem can be easily reproduced using the comms-sdk-web-getting-started demo. 

**Reproduction of the problem**
1. e.g. Firefox Desktop navigate to the URL https://developer.dolby.io/demos/comms-sdk-web-getting-started/index.html 
2. enter token and join the chat 
3. start Android Chrome or other Chromimum based browser (Edge, Brave)
4. navigate to https://developer.dolby.io/demos/comms-sdk-web-getting-started/index.html and log in with same token
5. join chat 
6. on mobile device remote and local streams will continue to run
7. however, remote view freezes on Firefox desktop.

**Comment by FabienLavocat** [comment]
Thank you for reporting this @Schaeri, I have tried to reproduce this problem but everything works well on my end. Could you please provide some extra information like the conference ID and some console logs from Firefox when it freezes.

**Comment by Schaeri** [comment]
We have created a video in which we show the problem with the Get Started demo. 

https://github.com/voxeet/voxeet-sdk-web/assets/15650359/0ab21949-9a54-44b9-8544-382e63ffda91

The setup is as follows: 

- The left side runs on a desktop computer Firefox version 113.0.1 on Windows 11. 
- On the mobile device on the right, Edge 113.0.1774.50 is running on Android 11. 
- The sound in the video has been removed for data protection reasons.

After a few seconds, the remote view freezes in Firefox on the desktop computer. Although the self-view continues to run in the Edge browser on the mobile device. The transmission of the audio signal is not affected. The two participants can continue to speak to each other and can hear each other as well. 

The console log in Firefox shows no outputs or errors after freezing. 

We have tested with various browsers on several mobile devices. We were able to reproduce the problem with Brave, Edge, and Chrome. We also tested in various networks, such as company-internal or public mobile networks. The problem occurs reliably here as well. 

If a Firefox browser is running on the mobile device, the problem does not occur. The video runs stably for a longer period of time.

**Comment by FabienLavocat** [comment]
Thanks a lot for sharing this video that demonstrate the problem. Could you please try to force a video resolution when joining the conference. Update this [line](https://github.com/dolbyio-samples/comms-sdk-web-getting-started/blob/master/video-calls/final/index.html#L135) from:
```js
const joinOptions = {
    constraints: { audio: true, video: true }
};
```
to something like:
```js
const joinOptions = {
    constraints: {
        audio: true,
        video: {
            height: 640,
            width: 480
        }
    }
};
```

**Comment by christianzingg** [comment]
> Thanks a lot for sharing this video that demonstrate the problem. Could you please try to force a video resolution when joining the conference. Update this [line](https://github.com/dolbyio-samples/comms-sdk-web-getting-started/blob/master/video-calls/final/index.html#L135) from:
> 
> ```js
> const joinOptions = {
>     constraints: { audio: true, video: true }
> };
> ```
> 
> to something like:
> 
> ```js
> const joinOptions = {
>     constraints: {
>         audio: true,
>         video: {
>             height: 640,
>             width: 480
>         }
>     }
> };
> ```

By forcing a video resolution, we can workaround the problem.

**Comment by FabienLavocat** [comment]
Thank you for the confirmation. It looks like a problem with Chromium on mobile (Android) devices.
