### ISSUE TITLE
Unable to get participants using the sdk

### ISSUE THREAD

**Issue by weiz18** [voxeet/voxeet-sdk-web#23]
**Issue**

Hey, on the latest version of the sdk, we are getting the following error when trying to access a list of participants  (https://docs.dolby.io/communications-apis/docs/js-client-sdk-conferenceservice#participants) 

**How to reproduce** 
`conference.participants.forEach`

**Error**

`Conference creation error TypeError: Cannot read properties of undefined (reading 'call')
    at get participants [as participants] (voxeet-sdk.js:2:1029478)` 

Thanks !

**Comment by FabienLavocat** [comment]
Try this syntax:
```js
[...VoxeetSDK.conference.participants].forEach((p) => console.log(p));
```

**Comment by weiz18** [comment]
Thanks @FabienLavocat , that works.   does that always return current conference ? i also tried `[...VoxeetSDK.conference.current.participants]` to have the current conference but seems to be failing

**Comment by FabienLavocat** [comment]
I was able to get this code to work without any issues
```js
VoxeetSDK.conference.current.participants.forEach((o, key) => console.log(key, o));
```
Which is similar to:
```js
VoxeetSDK.conference.participants.forEach((o, key) => console.log(key, o));
```

Could you please share a full code snippet from your app that is failing.

**Comment by weiz18** [comment]
Hey, @FabienLavocat, manage to find the cause. we were using promising chaining before and the conference must not be modified properly when joining a conference.  all good now. thanks for your help !
