### ISSUE TITLE
npm audit reports dependency on vulnerable version of axios

### ISSUE THREAD

**Issue by nemesisridiculii** [voxeet/voxeet-sdk-web#26]
I have a project that uses @dolbyio/comms-uikit-react@1.3.1 (the latest version as of this writing) which has @voxeet/voxeet-web-sdk@3.11.0 (also the current version). When I preform an `npm audit` in my project, I get a report that voxeet-web-sdk references a vulnerable version of axios. There is more information about the axios vulnerability here: https://github.com/advisories/GHSA-wf5p-g6vw-rhxx.

Are there plans to update this dependency to resolve this vulnerability?

**Comment by FabienLavocat** [comment]
Hi @nemesisridiculii, we have released the version [3.11.1](https://github.com/voxeet/voxeet-sdk-web/releases/tag/3.11.1) of the SDK that fixes this vulnerability issue.

**Comment by nemesisridiculii** [comment]
Looks good. Thank you for the update!
