### ISSUE TITLE
Updated stream is not found in participant.streams when streamUpdated called

### ISSUE THREAD

**Issue by yerim1210** [voxeet/voxeet-sdk-web#4]
### Context
I'm currently working on migrating web SDK from 2.4.0 to 3.3.0. 
> SDK settings:
> VoxeetSDK version: 3.3.0
> VoxeetSDK flavor: production
> Telemetry status: enabled

### Issue
When `streamUpdated` event is called, I've tried to find the same stream as the returning stream from `participant.streams` but could not find. I've tested this on `streamAdded` event and it had the stream. I simply used below code to print logs.

- **streamUpdated**
```
VoxeetSDK.conference.on('streamUpdated', (participant, stream) => {
  console.log(find(participant.streams, (s) => s.id === stream.id)); // return FALSE
});
```
- **streamAdded**
```
VoxeetSDK.conference.on('streamAdded', (participant, stream) => {
  console.log(find(participant.streams, (s) => s.id === stream.id)); // return TRUE
});
```

### Expected Result
I would expect the stream to be found in `participant.steams` as well on `streamUpdated`.

**Comment by FabienLavocat** [comment]
Apologies for the delay in the answer, your syntax for the `find` is not correct, try this:
```javascript
console.log(participant.streams.find((s) => s.id === stream.id));
```
