### ISSUE TITLE
Can't compile because need @dolby-dvc/dvwc, but not exist

### ISSUE THREAD

**Issue by cristoj** [voxeet/voxeet-sdk-web#5]
Hii, this package needs @dolby-dvc/dvwc, but doesn't exists in npm directory... How can I fix it????

Thanks

**Comment by FabienLavocat** [comment]
The `@dolby-dvc/dvwc` library is a devDependency, your npm script should not attempt to install it.
Could you please try the latest version of the package and share the error message.

**Comment by FabienLavocat** [comment]
This should have been fixed in the latest version of the SDK, please reopen if you still face this issue.

**Comment by mjohnson4** [comment]
Getting the same issue on the latest version (3.7.0) with Angular. @FabienLavocat  - Could you please check?

**Comment by FabienLavocat** [comment]
I was able to reproduce this error from a new Angular application using TypeScript. To remove this warning, please add the [skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck) flag with the value `true` in your `tsconfig.json`.
```json
"skipLibCheck": true
```
