### ISSUE TITLE
Voxeet does not work with Next.Js

### ISSUE THREAD

**Issue by nkdhamelia** [voxeet/voxeet-sdk-web#6]
Hi,
I am trying to use Voxeet in my brand new Nextjs project but I am getting the following error, Is there any recommended way to integrate SDK with nextjs project? Please advice 

![voxeet](https://user-images.githubusercontent.com/105836919/170189720-63c9dc9a-81ad-46d7-a0b8-a238c1ca0255.png)

**Comment by FabienLavocat** [comment]
Working with our support team on this issue

**Comment by FabienLavocat** [comment]
I'm going to post the solution here.

Please make sure that you will load the Voxeet SDK in your NextJs app client side only. Something like this:

```javascript
if(typeof window !== 'undefined') {
    const VoxeetSDK = require('@voxeet/voxeet-web-sdk');
    const init = VoxeetSDK.initializeToken.bind(VoxeetSDK);
    init(accessToken, refreshToken);
}
```
