### ISSUE TITLE
Build 3.5 is not stable at all

### ISSUE THREAD

**Issue by azeemgujjar** [voxeet/voxeet-sdk-web#7]
First issue is your all three voxeet-dvwc-worker.js, voxeet-sdk.js, voxeet-worklet.js should be on root its required.

After putting files on root then load  voxeet-sdk.js then if we refresh browser and join conference will through these errors.

![image](https://user-images.githubusercontent.com/4154532/172021076-bdc7a900-bd20-45ab-8525-6a63538818e3.png)

With every new build always release new sample code incase if there is any change we must acknowledged about new updates or required code changes.

**Comment by FabienLavocat** [comment]
I was able to make an existing sample to work properly with our SDK 3.5.0. You need to place the following files at the root of the website:
- voxeet-dvwc-worker.js
- voxeet-sdk.js
- voxeet-worklet.js
- dvwc_impl.wasm

This will be improved in an upcoming patch release of the SDK. In the meantime I published an update of a first sample application. You can see this [commit](https://github.com/dolbyio-samples/comms-sdk-web-sample/commit/f0b8ce2204e1816d1ff124bc391519eaef6166d8), I've added the 4 files to the root folder and you can see the result at this [location](https://dolbyio-samples.github.io/comms-sdk-web-sample/). I will update the other sample applications and add some documentation in the next hours.

**Comment by azeemgujjar** [comment]
> s will be improved in an upcoming patch release of the SDK.

Awesome @FabienLavocat Thanks for response.

Also this would be great if you can introduce 2 more API's as this is requirement in our case.

- StopAudio able to accept Array of Participant ID's except session participant.
- StopAudioAll able to stop all audio except session participant.

Right now we are running for loop to do achieve this with StopAudio and by passing each Participant.

**Comment by FabienLavocat** [comment]
Excellent, I'm glad to hear that you have been able to fix the issue.

For the two APIs, I will pass along the feature to our team and see what is possible. This would likely introduce a breaking change so I do not know if we will be able to do it in the SDK, but I am thinking about another possibility.
