### ISSUE TITLE
new Function is breaking csp rules for security

### ISSUE THREAD

**Issue by Tallyb** [voxeet/voxeet-sdk-web#9]
new Function is breaking unsafe_eval CSP rule. Is it possible to change ?

**Comment by FabienLavocat** [comment]
Could you please elaborate, what version of the SDK triggers this warning? What new function is this about?

**Comment by Tallyb** [comment]
I see it from 3.3.0 onward (possibly earlier, did not check). Since the code in GH is minified, I cannot link to it. 
You can search for `new Function` in the code. 
Function() is one of the things that breaks the unsafe_eval rule as you can read here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_eval_expressions
In 3.5.0 the following exists: 

new Function("return this")()}catch(e){"object"==typeof window&&(n=window)}e.exports=n}
Is it really necessary to use the new Function?

**Comment by FabienLavocat** [comment]
Thanks @Tallyb for reporting this, I will investigate and get back to you on this.

**Comment by FabienLavocat** [comment]
This unsafe_eval rule is coming from a dependency to our SDK and will be improved in SDK 3.8 so you won't see this warning anymore.

**Comment by rbonora** [comment]
Hi @FabienLavocat is the fix now available? thanks

**Comment by pnowa-dolby** [comment]
Hi @rbonora. The issue is fixed in Web SDK 3.7.0, if you search for `new Function` in voxeet-sdk.js there should be no results.
